# Generated by Django 5.1.6 on 2025-10-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notifications',
            table='user_notifications',
        ),
    ]
