# Generated by Django 5.1.6 on 2026-02-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_notifications_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='ls_aai_id',
        ),
    ]
