# Generated by Django 5.1.6 on 2025-03-06 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'persons_deleted',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('regulatory_framework', models.CharField(blank=True, max_length=255, null=True)),
                ('trial', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('pi', models.ForeignKey(blank=True, db_column='pi_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_pi_id', to='core.person')),
                ('project', models.ForeignKey(blank=True, db_column='project_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_project_id', to='core.project')),
            ],
            options={
                'db_table': 'studies',
                'ordering': ['id'],
            },
        ),
    ]
