# Generated by Django 5.1.6 on 2025-03-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_project_name_project_short_name_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start',
            new_name='start_date',
        ),
    ]
