# Generated by Django 5.1.6 on 2025-03-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_ga_number_project_ga_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ga_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
