# Generated by Django 5.1.6 on 2025-03-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_ga_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='short_name',
            new_name='short_title',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='name',
            new_name='title',
        ),
    ]
