# Generated by Django 5.1.6 on 2025-03-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_short_name_study_short_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='trial',
            new_name='trial_id',
        ),
    ]
