# Generated by Django 5.1.6 on 2025-03-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_trial_study_trial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='project',
            field=models.OneToOneField(blank=True, db_column='project_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_project_id', to='core.project'),
        ),
    ]
