# Generated by Django 5.1.6 on 2025-03-10 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_study_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudyCountry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lead_country', models.BooleanField(default=False)),
                ('submission', models.DateTimeField(blank=True, null=True)),
                ('approval', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_country_country_id', to='core.country')),
                ('study', models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_country_study_id', to='core.study')),
            ],
            options={
                'db_table': 'study_countries',
                'ordering': ['id'],
            },
        ),
    ]
