# Generated by Django 5.1.6 on 2025-03-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_country_studycountry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycountry',
            old_name='approval',
            new_name='approval_date',
        ),
        migrations.RenameField(
            model_name='studycountry',
            old_name='submission',
            new_name='submission_date',
        ),
    ]
