# Generated by Django 5.1.6 on 2025-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_studycountry_country_alter_studycountry_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycountry',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
