# Generated by Django 5.1.6 on 2025-03-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_studycountry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycountry',
            name='lead_country',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
