# Generated by Django 5.1.6 on 2025-03-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_studycountry_lead_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='core.project'),
        ),
    ]
