# Generated by Django 5.1.6 on 2025-05-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_study_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='short_name',
            new_name='iso3',
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
