# Generated by Django 5.1.6 on 2025-05-06 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_name_person_full_name_remove_person_surname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address_info', models.CharField(blank=True, max_length=255, null=True)),
                ('sas_verification', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, db_column='contact_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctu_study_id', to='core.person')),
                ('country', models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctu_country_id', to='core.country')),
            ],
            options={
                'db_table': 'ctus',
                'ordering': ['id'],
            },
        ),
    ]
