# Generated by Django 5.1.6 on 2025-05-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ctu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctu',
            name='address_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctu',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
