# Generated by Django 5.1.6 on 2025-05-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_ctu_address_info_alter_ctu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctu',
            name='country',
        ),
        migrations.RemoveField(
            model_name='ctu',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CTU',
        ),
    ]
