# Generated by Django 5.1.6 on 2025-05-22 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_studystatus'),
        ('core', '0020_remove_ctu_country_remove_ctu_contact_delete_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycountry',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_study_countries', to='context.country'),
        ),
        migrations.AlterField(
            model_name='studycountry',
            name='study',
            field=models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_study_countries', to='core.study'),
        ),
    ]
