# Generated by Django 5.1.6 on 2025-05-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_studystatus'),
        ('core', '0021_alter_studycountry_country_alter_studycountry_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycountry',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_study_countries', to='context.country'),
        ),
    ]
