# Generated by Django 5.1.6 on 2025-05-26 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_studystatus'),
        ('core', '0023_alter_studycountry_country_alter_studycountry_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCTU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site_number', models.IntegerField(blank=True, null=True)),
                ('patients_expected', models.IntegerField(blank=True, null=True)),
                ('recruitment_greenlight', models.DateTimeField(default=False)),
                ('mov_expected_number', models.IntegerField(blank=True, null=True)),
                ('pi_national_coordinator', models.BooleanField(default=False)),
                ('ctu', models.ForeignKey(blank=True, db_column='ctu_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_ctu_ctu_id', to='context.ctu')),
                ('pi', models.ForeignKey(blank=True, db_column='contact_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctu_study_id', to='core.person')),
                ('study', models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_ctu_study_id', to='core.study')),
            ],
            options={
                'db_table': 'study_ctus',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visit_type', models.CharField(blank=True, db_column='type', max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('greenlight', models.DateTimeField(blank=True, null=True)),
                ('pharmacy', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('report_sent', models.DateTimeField(blank=True, null=True)),
                ('report_approved', models.DateTimeField(blank=True, null=True)),
                ('study_ctu', models.ForeignKey(blank=True, db_column='study_ctu_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='core.studyctu')),
            ],
            options={
                'db_table': 'visits',
                'ordering': ['id'],
            },
        ),
    ]
