# Generated by Django 5.1.6 on 2025-05-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_studystatus'),
        ('core', '0024_studyctu_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyctu',
            name='study_country',
            field=models.ForeignKey(blank=True, db_column='study_country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_ctus', to='core.study'),
        ),
        migrations.AlterField(
            model_name='studyctu',
            name='ctu',
            field=models.ForeignKey(blank=True, db_column='ctu_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_ctus', to='context.ctu'),
        ),
        migrations.AlterField(
            model_name='studyctu',
            name='pi',
            field=models.ForeignKey(blank=True, db_column='pi_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_ctus', to='core.person'),
        ),
        migrations.AlterField(
            model_name='studyctu',
            name='study',
            field=models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_ctus', to='core.study'),
        ),
    ]
