# Generated by Django 5.1.6 on 2025-05-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_alter_ctu_country'),
        ('core', '0025_studyctu_study_country_alter_studyctu_ctu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycountry',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_countries', to='context.country'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='study_ctu',
            field=models.ForeignKey(blank=True, db_column='study_ctu_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.studyctu'),
        ),
    ]
