# Generated by Django 5.1.6 on 2025-05-28 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_studycountry_country_alter_visit_study_ctu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyctu',
            name='recruitment_greenlight',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyctu',
            name='study_country',
            field=models.ForeignKey(blank=True, db_column='study_country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_ctus', to='core.studycountry'),
        ),
    ]
