# Generated by Django 5.1.6 on 2025-06-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_studyctu_recruitment_greenlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyctu',
            name='site_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
