# Generated by Django 5.1.6 on 2025-06-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_studyctu_site_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyctu',
            name='mov_expected_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studyctu',
            name='patients_expected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
