# Generated by Django 5.1.6 on 2025-06-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_studyctu_mov_expected_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
