# Generated by Django 5.1.6 on 2025-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_study_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['id', 'order']},
        ),
        migrations.AddField(
            model_name='study',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
