# Generated by Django 5.1.6 on 2025-06-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_study_options_study_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='order',
            field=models.IntegerField(blank=True, db_column='s_order', null=True),
        ),
    ]
