# Generated by Django 5.1.6 on 2025-07-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_study_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='c_euco',
            field=models.ForeignKey(blank=True, db_column='c_euco_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.person'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_source',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_patients_expected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='first_patient_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='first_patient_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='population',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='recruitment_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='recruitment_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
