# Generated by Django 5.1.6 on 2025-07-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_project_c_euco_project_funding_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='funding_source',
        ),
    ]
