# Generated by Django 5.1.6 on 2025-07-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_fundingsource_service'),
        ('core', '0034_remove_project_funding_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_sources',
            field=models.ManyToManyField(to='context.fundingsource'),
        ),
    ]
