# Generated by Django 5.1.6 on 2025-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_fundingsource_service'),
        ('core', '0035_project_funding_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(to='context.service'),
        ),
    ]
