# Generated by Django 5.1.6 on 2025-07-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_fundingsource_service'),
        ('core', '0036_project_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding_sources',
            field=models.ManyToManyField(blank=True, null=True, to='context.fundingsource'),
        ),
    ]
