# Generated by Django 5.1.6 on 2025-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_fundingsource_service'),
        ('core', '0037_alter_project_funding_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding_sources',
            field=models.ManyToManyField(blank=True, default=[], to='context.fundingsource'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_patients_expected',
            field=models.CharField(blank=True, default=[], max_length=255),
        ),
    ]
