# Generated by Django 5.1.6 on 2025-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_fundingsource_service'),
        ('core', '0038_alter_project_funding_sources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, default=[], to='context.service'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_patients_expected',
            field=models.CharField(max_length=255),
        ),
    ]
