# Generated by Django 5.1.6 on 2025-07-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_fundingsource_service'),
        ('core', '0039_alter_project_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding_sources',
            field=models.ManyToManyField(blank=True, to='context.fundingsource'),
        ),
        migrations.AlterField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, to='context.service'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_patients_expected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
