# Generated by Django 5.1.6 on 2025-07-04 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0005_person_alter_ctu_contact'),
        ('core', '0040_alter_project_funding_sources_alter_project_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyctu',
            name='pi',
            field=models.ForeignKey(blank=True, db_column='pi_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_ctus', to='context.person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='c_euco',
            field=models.ForeignKey(blank=True, db_column='c_euco_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='context.person'),
        ),
        migrations.AlterField(
            model_name='study',
            name='pi',
            field=models.ForeignKey(blank=True, db_column='pi_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_pi_id', to='context.person'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
