# Generated by Django 5.1.6 on 2025-07-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_studyctu_pi_alter_project_c_euco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coordinator',
            field=models.CharField(blank=True, null=True),
        ),
    ]
