# Generated by Django 5.1.6 on 2025-07-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_project_coordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='first_patient_out',
            new_name='last_patient_out',
        ),
        migrations.AddField(
            model_name='study',
            name='trial_registration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
