# Generated by Django 5.1.6 on 2025-07-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_first_patient_out_study_last_patient_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='treatment_and_follow_up_duration_per_patient',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='treatment_period_per_patient',
            field=models.CharField(blank=True, null=True),
        ),
    ]
