# Generated by Django 5.1.6 on 2025-07-09 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0005_person_alter_ctu_contact'),
        ('core', '0044_study_treatment_and_follow_up_duration_per_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='study_ctu',
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site_number', models.CharField(blank=True, max_length=255, null=True)),
                ('patients_expected', models.CharField(blank=True, max_length=255, null=True)),
                ('recruitment_greenlight', models.DateTimeField(blank=True, null=True)),
                ('mov_expected_number', models.CharField(blank=True, max_length=255, null=True)),
                ('pi_national_coordinator', models.BooleanField(default=False)),
                ('ctu', models.ForeignKey(blank=True, db_column='ctu_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres', to='context.ctu')),
                ('pi', models.ForeignKey(blank=True, db_column='pi_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres', to='context.person')),
                ('study', models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='core.study')),
                ('study_country', models.ForeignKey(blank=True, db_column='study_country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='core.studycountry')),
            ],
            options={
                'db_table': 'centres',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='centre',
            field=models.ForeignKey(blank=True, db_column='centre_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.centre'),
        ),
        migrations.DeleteModel(
            name='StudyCTU',
        ),
    ]
