# Generated by Django 5.1.6 on 2025-07-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_visit_study_ctu_centre_visit_centre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='first_patient_visit',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='hospital',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='town',
            field=models.CharField(blank=True, null=True),
        ),
    ]
