# Generated by Django 5.1.6 on 2025-07-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_centre_first_patient_visit_centre_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='first_patient_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
