# Generated by Django 5.1.6 on 2025-07-10 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0005_person_alter_ctu_contact'),
        ('core', '0047_alter_centre_first_patient_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='ctu',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='study',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='study_country',
        ),
        migrations.CreateModel(
            name='StudyCTU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ctu', models.ForeignKey(blank=True, db_column='ctu_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_ctus', to='context.ctu')),
                ('study', models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_ctus', to='core.study')),
                ('study_country', models.ForeignKey(blank=True, db_column='study_country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_ctus', to='core.studycountry')),
            ],
            options={
                'db_table': 'study_ctus',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='centre',
            name='study_ctu',
            field=models.ForeignKey(blank=True, db_column='study_ctu_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres', to='core.studyctu'),
        ),
    ]
