# Generated by Django 5.1.6 on 2025-07-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_centre_ctu_remove_centre_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studycountry',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='studycountry',
            name='submission_date',
        ),
    ]
