# Generated by Django 5.1.6 on 2025-07-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_studycountry_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycountry',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True),
        ),
        migrations.AddField(
            model_name='studyctu',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True),
        ),
    ]
