# Generated by Django 5.1.6 on 2025-07-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_studycountry_order_studyctu_order_alter_study_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studycountry',
            options={'ordering': ['id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='studyctu',
            options={'ordering': ['id', 'order']},
        ),
    ]
