# Generated by Django 5.1.6 on 2025-07-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_studycountry_options_alter_studyctu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='studycountry',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='studyctu',
            options={'ordering': ['order']},
        ),
    ]
