# Generated by Django 5.1.6 on 2025-07-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_study_options_alter_studycountry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centre',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='centre',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True),
        ),
    ]
