# Generated by Django 5.1.6 on 2025-08-19 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0007_complextrialtype_medicalfield_population'),
        ('core', '0053_alter_centre_options_centre_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='trial_registration',
            new_name='trial_registration_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='c_euco',
        ),
        migrations.RemoveField(
            model_name='project',
            name='services',
        ),
        migrations.RemoveField(
            model_name='study',
            name='category',
        ),
        migrations.RemoveField(
            model_name='study',
            name='trial_id',
        ),
        migrations.AddField(
            model_name='project',
            name='public_summary',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='c_euco',
            field=models.ForeignKey(blank=True, db_column='c_euco_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='context.person'),
        ),
        migrations.AddField(
            model_name='study',
            name='complex_trial_design',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='complex_trial_type',
            field=models.ForeignKey(blank=True, db_column='complex_trial_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='context.complextrialtype'),
        ),
        migrations.AddField(
            model_name='study',
            name='coordinating_country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='context.country'),
        ),
        migrations.AddField(
            model_name='study',
            name='medical_fields',
            field=models.ManyToManyField(blank=True, to='context.medicalfield'),
        ),
        migrations.AddField(
            model_name='study',
            name='rare_diseases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='services',
            field=models.ManyToManyField(blank=True, to='context.service'),
        ),
        migrations.AlterField(
            model_name='study',
            name='pi',
            field=models.ForeignKey(blank=True, db_column='pi_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='context.person'),
        ),
        migrations.RemoveField(
            model_name='study',
            name='population',
        ),
        migrations.AddField(
            model_name='study',
            name='population',
            field=models.ManyToManyField(blank=True, to='context.population'),
        ),
    ]
