# Generated by Django 5.1.6 on 2025-08-20 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0008_organisation'),
        ('core', '0054_rename_trial_registration_study_trial_registration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor_organisation',
            field=models.ForeignKey(blank=True, db_column='organisation_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='context.organisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coordinator',
            field=models.ForeignKey(blank=True, db_column='organisation_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='context.organisation'),
        ),
    ]
