# Generated by Django 5.1.6 on 2025-08-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_study_sponsor_study_sponsor_organisation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='population',
            new_name='populations',
        ),
    ]
