# Generated by Django 5.1.6 on 2025-08-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0010_organisation_short_name'),
        ('core', '0056_rename_population_study_populations'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='sponsor_country',
            field=models.ForeignKey(blank=True, db_column='sponsor_country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='context.country'),
        ),
        migrations.AlterField(
            model_name='study',
            name='coordinating_country',
            field=models.ForeignKey(blank=True, db_column='coordinating_country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='context.country'),
        ),
    ]
