# Generated by Django 5.1.6 on 2025-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_study_sponsor_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='treatment_and_follow_up_duration_per_patient_unit',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='treatment_period_per_patient_unit',
            field=models.CharField(blank=True, null=True),
        ),
    ]
