# Generated by Django 5.1.6 on 2025-08-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_study_treatment_and_follow_up_duration_per_patient_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='treatment_period_per_patient',
            new_name='treatment_duration_per_patient',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='treatment_period_per_patient_unit',
            new_name='treatment_duration_per_patient_unit',
        ),
    ]
