# Generated by Django 5.1.6 on 2025-08-26 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0011_alter_person_country'),
        ('core', '0059_rename_treatment_period_per_patient_study_treatment_duration_per_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coordinator',
            field=models.ForeignKey(blank=True, db_column='organisation_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='context.organisation'),
        ),
        migrations.AlterField(
            model_name='study',
            name='complex_trial_type',
            field=models.ForeignKey(blank=True, db_column='complex_trial_type_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='context.complextrialtype'),
        ),
        migrations.AlterField(
            model_name='study',
            name='coordinating_country',
            field=models.ForeignKey(blank=True, db_column='coordinating_country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='context.country'),
        ),
        migrations.AlterField(
            model_name='study',
            name='sponsor_country',
            field=models.ForeignKey(blank=True, db_column='sponsor_country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='context.country'),
        ),
        migrations.AlterField(
            model_name='study',
            name='sponsor_organisation',
            field=models.ForeignKey(blank=True, db_column='organisation_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='context.organisation'),
        ),
    ]
