# Generated by Django 5.1.6 on 2025-10-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0011_alter_person_country'),
        ('core', '0060_alter_project_coordinator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='project',
            name='coordinating_institution',
            field=models.ForeignKey(blank=True, db_column='coordinating_institution_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='context.organisation'),
        ),
    ]
