# Generated by Django 5.1.6 on 2025-10-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0011_alter_person_country'),
        ('core', '0061_remove_project_coordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coordinator',
            field=models.ForeignKey(blank=True, db_column='coordinator_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='context.person'),
        ),
    ]
