# Generated by Django 5.1.6 on 2025-10-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0011_alter_person_country'),
        ('core', '0062_project_coordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='total_patients_expected',
        ),
        migrations.RemoveField(
            model_name='study',
            name='pi',
        ),
        migrations.AddField(
            model_name='study',
            name='coordinating_investigator',
            field=models.ForeignKey(blank=True, db_column='coordinating_investigator_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='context.person'),
        ),
        migrations.AlterField(
            model_name='study',
            name='sponsor_country',
            field=models.ForeignKey(blank=True, db_column='sponsor_country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='context.country'),
        ),
    ]
