# Generated by Django 5.1.6 on 2025-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_project_total_patients_expected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='total_patients_expected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
