# Generated by Django 5.1.6 on 2025-10-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_study_total_patients_expected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='recruitment_end',
        ),
        migrations.RemoveField(
            model_name='study',
            name='recruitment_start',
        ),
        migrations.AddField(
            model_name='study',
            name='recruitment_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
