# Generated by Django 5.1.6 on 2025-10-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_study_recruitment_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='recruitment_periodèunit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='treatment_and_follow_up_duration_per_patient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='treatment_and_follow_up_duration_per_patient_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='treatment_duration_per_patient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='treatment_duration_per_patient_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
