# Generated by Django 5.1.6 on 2025-10-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_study_recruitment_periodèunit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='recruitment_periodèunit',
            new_name='recruitment_period_unit',
        ),
    ]
