# Generated by Django 5.1.6 on 2025-10-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_rename_recruitment_periodèunit_study_recruitment_period_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studycountry',
            name='lead_country',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('authority', models.CharField(blank=True, null=True)),
                ('notification_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('study_country', models.ForeignKey(blank=True, db_column='study_country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.studycountry')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('authority', models.CharField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('protocol_approval_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('amendment', models.BooleanField(default=False)),
                ('amendment_reason', models.CharField(blank=True, null=True)),
                ('study_country', models.ForeignKey(blank=True, db_column='study_country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.studycountry')),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['id'],
            },
        ),
    ]
