# Generated by Django 5.1.6 on 2025-10-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_studycountry_lead_country_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True),
        ),
    ]
