# Generated by Django 5.1.6 on 2025-10-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_submission_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='amendment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='amendment_reason',
        ),
    ]
