# Generated by Django 5.1.6 on 2025-10-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_submission_options_remove_submission_amendment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.submission')),
                ('amendment', models.BooleanField(default=False)),
                ('amendment_reason', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amendments',
                'ordering': ['order'],
            },
            bases=('core.submission',),
        ),
        migrations.CreateModel(
            name='OtherNotification',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.submission')),
            ],
            options={
                'db_table': 'other_notifications',
                'ordering': ['id'],
            },
            bases=('core.submission',),
        ),
    ]
