# Generated by Django 5.1.6 on 2025-10-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_amendment_othernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othernotification',
            name='submission_ptr',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_amendment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_other_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Amendment',
        ),
        migrations.DeleteModel(
            name='OtherNotification',
        ),
    ]
