# Generated by Django 5.1.6 on 2025-10-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_othernotification_submission_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='amendment_reason',
            field=models.CharField(blank=True, null=True),
        ),
    ]
