# Generated by Django 5.1.6 on 2025-11-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0012_hospital'),
        ('core', '0073_submission_amendment_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='town',
        ),
        migrations.AlterField(
            model_name='centre',
            name='hospital',
            field=models.ForeignKey(blank=True, db_column='hospital_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres', to='context.hospital'),
        ),
    ]
