# Generated by Django 5.1.6 on 2025-11-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_centre_town_alter_centre_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='recruitment_greenlight',
        ),
    ]
