# Generated by Django 5.1.6 on 2025-11-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_centre_recruitment_greenlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='protocol_approved_version',
            field=models.CharField(blank=True, null=True),
        ),
    ]
