# Generated by Django 5.1.6 on 2025-11-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_submission_protocol_approved_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='site_number_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyctu',
            name='lead_ctu',
            field=models.BooleanField(default=False),
        ),
    ]
