# Generated by Django 5.1.6 on 2025-11-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0012_hospital'),
        ('core', '0077_centre_site_number_flag_studyctu_lead_ctu'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyctu',
            name='services',
            field=models.ManyToManyField(blank=True, to='context.service'),
        ),
    ]
