# Generated by Django 5.1.6 on 2025-11-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0013_regulatoryframeworkdetail'),
        ('core', '0078_studyctu_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='regulatory_framework_details',
            field=models.ManyToManyField(blank=True, to='context.regulatoryframeworkdetail'),
        ),
    ]
