# Generated by Django 5.1.6 on 2026-01-07 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0013_regulatoryframeworkdetail'),
        ('core', '0079_study_regulatory_framework_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='agreement_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='agreement_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='lead_ctu',
            field=models.ForeignKey(blank=True, db_column='lead_ctu_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='context.ctu'),
        ),
    ]
