# Generated by Django 5.1.6 on 2026-01-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_study_agreement_signed_study_agreement_signed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('authority', models.CharField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('notification_submitted', models.CharField(blank=True, max_length=100, null=True)),
                ('is_ctis', models.BooleanField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, db_column='order', null=True)),
                ('study_country', models.ForeignKey(blank=True, db_column='study_country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.studycountry')),
            ],
            options={
                'db_table': 'safety_notifications',
                'ordering': ['order'],
            },
        ),
    ]
