# Generated by Django 5.1.6 on 2026-01-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_safetynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetynotification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='safetynotification',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
