# Generated by Django 5.1.6 on 2026-01-12 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0015_safetynotificationtype'),
        ('core', '0082_safetynotification_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetynotification',
            name='is_ctis',
        ),
        migrations.AlterField(
            model_name='safetynotification',
            name='notification_type',
            field=models.ForeignKey(blank=True, db_column='safety_notification_type_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_notifications', to='context.safetynotificationtype'),
        ),
        migrations.AlterField(
            model_name='safetynotification',
            name='study_country',
            field=models.ForeignKey(blank=True, db_column='study_country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_notifications', to='core.studycountry'),
        ),
    ]
