# Generated by Django 5.1.6 on 2026-01-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0016_authority'),
        ('core', '0083_remove_safetynotification_is_ctis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetynotification',
            name='authority',
            field=models.ForeignKey(blank=True, db_column='authority_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_notifications', to='context.authority'),
        ),
    ]
