# Generated by Django 5.1.6 on 2026-01-14 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_safetynotification_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to_field="iso2", db_column='country_id', blank=True, null=True, related_name='study_countries', default=None, to='context.country'),
        ),
        migrations.AlterField(
            model_name='study',
            name='sponsor_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to_field="iso2", db_column='sponsor_country_id', blank=True, null=True, related_name='studies', default=None, to='context.country'),
        ),
        migrations.AlterField(
            model_name='study',
            name='coordinating_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to_field="iso2", db_column='coordinating_country_id', blank=True, null=True, related_name='studies', default=None, to='context.country'),
        ),
    ]
