# Generated by Django 5.1.6 on 2026-01-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_country_fks_to_field_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='coordinating_country',
        ),
        migrations.RemoveField(
            model_name='study',
            name='sponsor_country',
        ),
        migrations.RemoveField(
            model_name='studycountry',
            name='country',
        ),
    ]
