# Generated by Django 5.1.6 on 2026-01-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0019_country_fks_to_field_fix'),
        ('core', '0086_remove_study_coordinating_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='coordinating_country',
            field=models.ForeignKey(blank=True, db_column='coordinating_country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='context.country'),
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor_country',
            field=models.ForeignKey(blank=True, db_column='sponsor_country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='context.country'),
        ),
        migrations.AddField(
            model_name='studycountry',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_countries', to='context.country'),
        ),
    ]
