# Generated by Django 5.1.6 on 2026-01-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0022_alter_ctu_country_alter_organisation_country'),
        ('core', '0087_study_coordinating_country_study_sponsor_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycountry',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_countries', to='context.country'),
        ),
    ]
