# Generated by Django 5.1.6 on 2026-01-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_studycountry_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetynotification',
            name='notification_submitted',
        ),
        migrations.RemoveField(
            model_name='safetynotification',
            name='study_country',
        ),
        migrations.AddField(
            model_name='safetynotification',
            name='not_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='uses_ctis_for_safety_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studycountry',
            name='safety_notifications',
            field=models.ManyToManyField(blank=True, to='core.safetynotification'),
        ),
    ]
