# Generated by Django 5.1.6 on 2026-01-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_remove_safetynotification_notification_submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('stage', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_period_project_id', to='core.project')),
            ],
            options={
                'db_table': 'reporting_periods',
                'ordering': ['stage'],
            },
        ),
    ]
