# Generated by Django 5.1.6 on 2026-01-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_reportingperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingperiod',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='core.project'),
        ),
    ]
