# Generated by Django 5.1.6 on 2026-01-30 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0023_visittype'),
        ('core', '0091_alter_reportingperiod_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='report_approved',
            new_name='report_approved_date',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='report_sent',
            new_name='report_sent_date',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='date',
            new_name='visit_date',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='greenlight',
        ),
        migrations.AddField(
            model_name='centre',
            name='recruitment_greenlight',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='duration_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.ForeignKey(blank=True, db_column='visit_type', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='context.visittype'),
        ),
    ]
