# Generated by Django 5.1.6 on 2026-01-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_rename_report_approved_visit_report_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='report_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='report_sent',
            field=models.BooleanField(default=False),
        ),
    ]
