# Generated by Django 5.1.6 on 2026-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_visit_report_approved_visit_report_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='visit',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True),
        ),
    ]
