# Generated by Django 5.1.6 on 2026-02-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0024_ctustatus'),
        ('core', '0094_alter_visit_options_visit_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTUAgreement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('signed', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, db_column='order', null=True)),
                ('ctu_status', models.ForeignKey(blank=True, db_column='ctu_status_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctu_agreements', to='context.ctustatus')),
                ('study_ctu', models.ForeignKey(blank=True, db_column='study_ctu_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctu_agreements', to='core.studyctu')),
            ],
            options={
                'db_table': 'ctu_agreements',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTUAgreementAmendment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, db_column='order', null=True)),
                ('ctu_agreement', models.ForeignKey(blank=True, db_column='ctu_agreement_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctu_agreement_amendments', to='core.ctuagreement')),
            ],
            options={
                'db_table': 'ctu_agremeent_amendments',
                'ordering': ['order'],
            },
        ),
    ]
