# Generated by Django 5.1.6 on 2026-02-06 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_ctuagreement_ctuagreementamendment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='core.project'),
        ),
    ]
