# Generated by Django 5.1.6 on 2026-02-09 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0024_ctustatus'),
        ('core', '0096_alter_study_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='c_euco',
            field=models.ForeignKey(blank=True, db_column='c_euco_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies_from_c_euco', to='context.person'),
        ),
        migrations.AlterField(
            model_name='study',
            name='coordinating_country',
            field=models.ForeignKey(blank=True, db_column='coordinating_country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies_from_coordinating_country', to='context.country'),
        ),
        migrations.AlterField(
            model_name='study',
            name='coordinating_investigator',
            field=models.ForeignKey(blank=True, db_column='coordinating_investigator_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies_from_coordinating_investigator', to='context.person'),
        ),
        migrations.AlterField(
            model_name='study',
            name='sponsor_country',
            field=models.ForeignKey(blank=True, db_column='sponsor_country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies_from_sponsor_country', to='context.country'),
        ),
    ]
