# Generated by Django 5.1.6 on 2026-02-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_alter_study_c_euco_alter_study_coordinating_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='authority',
        ),
    ]
