# Generated by Django 5.1.6 on 2026-02-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0024_ctustatus'),
        ('core', '0098_remove_notification_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='authority',
            field=models.ForeignKey(blank=True, db_column='authority_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='context.authority'),
        ),
        migrations.AddField(
            model_name='submission',
            name='authority',
            field=models.ForeignKey(blank=True, db_column='authority_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='context.authority'),
        ),
    ]
