# Generated by Django 5.1.6 on 2026-02-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_notification_authority_submission_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='not_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='not_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
