# Generated by Django 5.1.6 on 2026-09-16 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0025_ctucontractingentity'),
        ('core', '0100_notification_not_applicable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyctu',
            name='ctu_contracting_entity',
            field=models.ForeignKey(blank=True, db_column='ctu_contracting_entity_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_ctus', to='context.ctucontractingentity'),
        ),
    ]
