# Generated by Django 5.1.6 on 2026-03-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_notification_not_applicable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pubmed_url', models.CharField(blank=True, max_length=500, null=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.project')),
                ('study', models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.study')),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['id'],
            },
        ),
    ]