# Generated by Django 5.1.6 on 2026-04-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_publication'),
        ('core', '0100_notification_not_applicable_and_more'),
    ]

    operations = [
    ]
