# Generated by Django 5.1.6 on 2026-09-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_studyctu_ctu_contracting_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctuagreement',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctuagreement',
            name='draft_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctuagreement',
            name='signed_by_ctu_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctuagreement',
            name='signed_by_ecrin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctuagreementamendment',
            name='new_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctuagreementamendment',
            name='signed_by_ctu_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctuagreementamendment',
            name='signed_by_ecrin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
