# Generated by Django 5.1.6 on 2026-09-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_study_ecrin_contracting_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAgreement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('draft_sent_date', models.DateTimeField(blank=True, null=True)),
                ('signed_by_sponsor_date', models.DateTimeField(blank=True, null=True)),
                ('signed_by_ecrin_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, db_column='order', null=True)),
                ('study', models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_agreements', to='core.study')),
            ],
            options={
                'db_table': 'study_agreements',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudyAgreementAmendment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('signed_by_sponsor_date', models.DateTimeField(blank=True, null=True)),
                ('signed_by_ecrin_date', models.DateTimeField(blank=True, null=True)),
                ('new_end_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, db_column='order', null=True)),
                ('study_agreement', models.ForeignKey(blank=True, db_column='study_agreement_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_agreement_amendments', to='core.studyagreement')),
            ],
            options={
                'db_table': 'study_agreement_amendments',
                'ordering': ['order'],
            },
        ),
    ]
