# Generated by Django 5.1.6 on 2026-05-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_publication_remove_study_add_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ecrin_employee_in_authors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_acknowledging_ecrin',
            field=models.BooleanField(default=False),
        ),
    ]
