# Generated by Django 5.1.6 on 2026-09-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_ctuagreement_comment_ctuagreement_draft_sent_date_and_more'),
        ('core', '0103_publication_ecrin_employee_in_authors_and_more'),
    ]

    operations = [
    ]
