# Generated by Django 5.1.6 on 2026-09-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_studyagreement_studyagreementamendment'),
        ('core', '0103_publication_ecrin_employee_in_authors_and_more'),
    ]

    operations = [
    ]
