# Generated by Django 5.1.6 on 2026-09-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_merge_20260918_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['order']},
        ),
    ]
