# Generated by Django 5.1.6 on 2026-09-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_merge_20260918_1259'),
        ('core', '0105_alter_publication_options'),
    ]

    operations = [
    ]
