# Generated by Django 5.1.6 on 2026-09-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_merge_20260918_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='core.project'),
        ),
    ]
