# Generated by Django 5.1.6 on 2026-10-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0031_remove_ctu_contact'),
        ('core', '0107_alter_study_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyctu',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_ctus', to='context.person'),
        ),
    ]
