# Generated by Django 5.1.6 on 2026-10-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_studyctu_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyctu',
            old_name='contact',
            new_name='contact_person',
        ),
    ]
