# Generated by Django 5.1.6 on 2026-10-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_rename_contact_studyctu_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='pharmacy',
        ),
    ]
