# Generated by Django 5.1.6 on 2026-10-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_remove_visit_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='pharmacy',
            field=models.BooleanField(default=False),
        ),
    ]
