# Generated by Django 5.1.6 on 2026-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_alter_project_name_alter_project_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='ecrin_acknowledgement',
            field=models.BooleanField(default=False),
        ),
    ]
