# Generated by Django 5.1.6 on 2026-10-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_study_ecrin_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='competitive_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
