# Generated by Django 5.1.6 on 2026-10-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_centre_competitive_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='private_funding_details',
            field=models.CharField(blank=True, null=True),
        ),
    ]
