# Generated by Django 5.1.6 on 2025-05-19 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0020_remove_ctu_country_remove_ctu_contact_delete_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('iso2', models.CharField(blank=True, max_length=255, null=True)),
                ('iso3', models.CharField(blank=True, max_length=255, null=True)),
                ('continent', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CTU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address_info', models.TextField(blank=True, null=True)),
                ('sas_verification', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, db_column='contact_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctu_study_id', to='core.person')),
                ('country', models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctu_country_id', to='context.country')),
            ],
            options={
                'db_table': 'ctus',
                'ordering': ['id'],
            },
        ),
    ]
