# Generated by Django 5.1.6 on 2025-05-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_studystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctu',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctu_country_id', to='context.country'),
        ),
    ]
