# Generated by Django 5.1.6 on 2025-07-04 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_fundingsource_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'persons',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='ctu',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctu_study_id', to='context.person'),
        ),
    ]
