# Generated by Django 5.1.6 on 2025-08-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0005_person_alter_ctu_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='context.country'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_euco',
            field=models.BooleanField(default=False),
        ),
    ]
