# Generated by Django 5.1.6 on 2025-08-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0006_person_country_person_is_euco'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexTrialType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'complex_trial_types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'medical_fields',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'populations',
                'ordering': ['id'],
            },
        ),
    ]
