# Generated by Django 5.1.6 on 2025-08-20 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0007_complextrialtype_medicalfield_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='context.country')),
            ],
            options={
                'db_table': 'organisations',
                'ordering': ['id'],
            },
        ),
    ]
