# Generated by Django 5.1.6 on 2025-08-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0008_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complextrialtype',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='fundingsource',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='medicalfield',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='population',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='value',
        ),
    ]
