# Generated by Django 5.1.6 on 2025-08-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0009_rename_name_complextrialtype_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='short_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
