# Generated by Django 5.1.6 on 2025-11-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0012_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryFrameworkDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'regulatory_framework_details',
                'ordering': ['id'],
            },
        ),
    ]
