# Generated by Django 5.1.6 on 2026-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0013_regulatoryframeworkdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctu',
            name='manual_add',
            field=models.BooleanField(default=False),
        ),
    ]
