# Generated by Django 5.1.6 on 2026-01-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0014_ctu_manual_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyNotificationType',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'safety_notification_types',
                'ordering': ['code'],
            },
        ),
    ]
