# Generated by Django 5.1.6 on 2026-01-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0015_safetynotificationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'authorities',
                'ordering': ['code'],
            },
        ),
    ]
