# Generated by Django 5.1.6 on 2026-01-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0016_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_in_eea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='is_in_eu',
            field=models.BooleanField(default=False),
        ),
    ]
