# Generated by Django 5.1.6 on 2026-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0017_country_is_in_eea_country_is_in_eu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['iso2']},
        ),
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(default=0, max_length=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(default=0, max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
