# Generated by Django 5.1.6 on 2026-01-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0018_alter_country_options_remove_country_id_and_more'),
    ]

    operations = [
        # Didn't do anything because altering "to_field" for an FK field requires removing and re-adding the field (altering field manually does not work)
    ]
