# Generated by Django 5.1.6 on 2026-01-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0019_country_fks_to_field_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctu',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
    ]
