# Generated by Django 5.1.6 on 2026-01-14 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0020_remove_ctu_country_remove_hospital_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctu',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctu_country_id', to='context.country'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='context.country'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='context.country'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='context.country'),
        ),
    ]
