# Generated by Django 5.1.6 on 2026-01-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0021_ctu_country_hospital_country_organisation_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctu',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctu_country_id', to='context.country'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations', to='context.country'),
        ),
    ]
