# Generated by Django 5.1.6 on 2026-01-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0022_alter_ctu_country_alter_organisation_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'visit_types',
                'ordering': ['code'],
            },
        ),
    ]
