# Generated by Django 5.1.6 on 2026-02-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0023_visittype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTUStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ctu_statuses',
                'ordering': ['id'],
            },
        ),
    ]
