# Generated by Django 5.1.6 on 2026-09-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0024_ctustatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcrinContractingEntity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ecrin_contracting_entities',
                'ordering': ['id'],
            },
        ),
    ]
