# Generated by Django 5.1.6 on 2026-03-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0024_ctustatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctu',
            name='sas_verification',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
