# Generated by Django 5.1.6 on 2026-03-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0024_ctustatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
