# Generated by Django 5.1.6 on 2026-03-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0025_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
