# Generated by Django 5.1.6 on 2026-04-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0026_ctu_sharepoint_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctu',
            name='sas_verification',
        ),
    ]
