# Generated by Django 5.1.6 on 2026-04-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0026_alter_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctu',
            name='sharepoint_item_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
