# Generated by Django 5.1.6 on 2026-09-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0026_seed_ctu_contracting_entities'),
        ('context', '0027_remove_ctu_sas_verification'),
    ]

    operations = [
    ]
