# Generated by Django 5.1.6 on 2026-09-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0025_ecrincontractingentity'),
        ('context', '0027_remove_ctu_sas_verification'),
    ]

    operations = [
    ]
