# Generated by Django 5.1.6 on 2026-04-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0025_alter_ctu_sas_verification'),
        ('context', '0027_ctu_sharepoint_item_id'),
    ]

    operations = [
    ]
