# Generated by Django 5.1.6 on 2026-09-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0028_merge_20260918_1259'),
        ('context', '0029_seed_ecrin_contracting_entities'),
    ]

    operations = [
    ]
