# Generated by Django 5.1.6 on 2026-10-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0030_merge_20260918_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctu',
            name='contact',
        ),
    ]
