# Generated by Django 5.1.6 on 2026-10-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0031_remove_ctu_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
    ]
