# Generated by Django 5.1.6 on 2026-10-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0032_remove_person_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
